<?php
    /*define('MYSQL_HOST','localhost');
    define('MYSQL_DATABASE','fhr');
    define('MYSQL_USER','root');
    define('MYSQL_PASS','');*/
    define('MYSQL_HOST','localhost');
    define('MYSQL_DATABASE','id19412630_fh');
    define('MYSQL_USER','id19412630_luiz');
    define('MYSQL_PASS','}M2sJ${|PS[hIVb8');
?>